### ISSUE TITLE
Logo / Branding

### ISSUE THREAD

**Issue by CLTJared** [dcast217/Car-Rental#7]
Generate a business name & logo

**Comment by CLTJared** [comment]
Assigned to @dcast217 to review & provide options.

**Comment by dcast217** [comment]
![image](https://github.com/dcast217/Car-Rental/assets/151418582/75cca67c-5d07-4df4-972e-73addcff753d)

**Comment by CLTJared** [comment]
![Torq](https://github.com/dcast217/Car-Rental/assets/119962687/a98402fc-97de-465d-a6cf-3ea36463710d)

Thinking column 1, row 2 or column 6 row 1.
